---
galaxy_info:
  author: Aleksandr Kostyrev
  description: Installs Koji's koji-builder for RedHat
  license: license (GPLv3)
  min_ansible_version: 1.8.4
  platforms:
  - name: EL
    versions:
    - 6
    - 7    
  categories:
  - development
  - packaging
  - system
dependencies:
- { role: patrik.uytterhoeven.PostgreSQL-For-RHEL6x }
